// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOjEVXe3n6oO607fzHuOdFzZ5YXJ415hc',
    appId: '1:807130772509:web:d00a39c07aaf881d9dc2f4',
    messagingSenderId: '807130772509',
    projectId: 'track-drive-web',
    authDomain: 'track-drive-web.firebaseapp.com',
    storageBucket: 'track-drive-web.firebasestorage.app',
    measurementId: 'G-L9C5N0MN44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUeTaO9BhiHy0_fbiF8XRFQ7Iwr7d7B48',
    appId: '1:807130772509:android:d21b63626f42e6f59dc2f4',
    messagingSenderId: '807130772509',
    projectId: 'track-drive-web',
    storageBucket: 'track-drive-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9tIpObd9uowYXPqY3WaxJT1Kv1PFywhI',
    appId: '1:807130772509:ios:8f7eed17fd0d778f9dc2f4',
    messagingSenderId: '807130772509',
    projectId: 'track-drive-web',
    storageBucket: 'track-drive-web.firebasestorage.app',
    iosBundleId: 'com.example.travelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9tIpObd9uowYXPqY3WaxJT1Kv1PFywhI',
    appId: '1:807130772509:ios:8f7eed17fd0d778f9dc2f4',
    messagingSenderId: '807130772509',
    projectId: 'track-drive-web',
    storageBucket: 'track-drive-web.firebasestorage.app',
    iosBundleId: 'com.example.travelsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOjEVXe3n6oO607fzHuOdFzZ5YXJ415hc',
    appId: '1:807130772509:web:2874ca7364c2ed7e9dc2f4',
    messagingSenderId: '807130772509',
    projectId: 'track-drive-web',
    authDomain: 'track-drive-web.firebaseapp.com',
    storageBucket: 'track-drive-web.firebasestorage.app',
    measurementId: 'G-PRVZLW0X9S',
  );
}
